### PR TITLE
Add more developer resources

### PR DESCRIPTION
**Pull request by 0xSimeon**
I updated the readme with more resources plus some cleanup to make it better. I also added a contribution guide so other users would have an idea about how to contribute to the repo.

### CODE REVIEW

**Comment by vivmost** [comment]
Thank you @simeon4real for the contribution.

**Comment by 0xSimeon** [comment]
Happy I could help @vivmost . Looks like your repo isn't participating in #hacktoberfest?

**Comment by vivmost** [comment]
I think any open source repo works fine with hacktoberfest , maybe new rules have been implemented that I am not aware of.
You can check out on their official website.

**Comment by 0xSimeon** [comment]
> I think any open source repo works fine with hacktoberfest , maybe new rules have been implemented that I am not aware of.
> You can check out on their official website.

Should be. Although your repo doesn't qualify right now. Says it's something to do with adding the "HacktoberFest topic" whatever that means.

**Comment by 0xSimeon** [comment]
Happy to contribute either way 😌

**Pull request merged**
